export const SITE = {
  name: "Backyard Bobby's",
  tagline: "Anne Arundel County's Trusted Outdoor Living Experts",
  phone: "443-875-8550",
  phoneTel: "tel:+14438758550",
  phoneSms: "sms:+14438758550",
  email: "info@backyardbobbys.com",
  license: "MHIC #05-163777",
  domain: "backyardbobbys.com",
  url: "https://backyardbobbys.com",
  address: {
    region: "Anne Arundel County",
    state: "Maryland",
    stateCode: "MD",
  },
} as const;

export interface CityEntry {
  name: string;
  slug: string;
  county: string;
  nearby: string[];
  headline: string;
  subheadline: string;
  localDescription: string;
  topServices: string[];
  localAngle: string;
  permitNote: string;
  faqs: { question: string; answer: string }[];
}

export const CITY_DATA: CityEntry[] = [
  {
    name: "Annapolis",
    slug: "annapolis",
    county: "Anne Arundel County",
    nearby: ["arnold", "severna-park", "edgewater", "parole", "riva", "crownsville"],
    headline: "Licensed Outdoor Construction in Maryland's Capital City",
    subheadline: "From waterfront hardscaping along Spa Creek to patio installations in Eastport and West Annapolis, Bobby's crew knows how to build in a city where history, salt air, and strict permitting all come into play.",
    localDescription: "Annapolis sits where the Severn River meets the Chesapeake Bay — which means waterfront properties, tidal influence on soil conditions, and the Historic District's additional permitting layer. Many homes here have compact yards that demand smart design to maximize outdoor living space. Bobby's crew has worked across downtown Annapolis, Eastport, West Annapolis, Hillsmere, and the Naval Academy-area neighborhoods.",
    topServices: ["Hardscaping", "Stamped Concrete", "Fencing", "Decks"],
    localAngle: "Properties near the waterfront often have high water tables and clay-heavy Coastal Plain soil, which means drainage has to be engineered into every patio and walkway — not bolted on as an afterthought. Bobby's team grades, compacts, and builds with these conditions in mind on every Annapolis project.",
    permitNote: "City of Annapolis fence permits require a scaled drawing showing the fence location, dimensions, and relationship to property lines. Properties in the Historic District need additional Historic Preservation Division approval before any exterior work begins. Waterfront properties may trigger stormwater review and Army Corps permits for work near the mean high tide line.",
    faqs: [
      { question: "Do I need a Historic District permit for a new fence or patio in downtown Annapolis?", answer: "If your property is within the Annapolis Historic District, yes — the Historic Preservation Division reviews all exterior changes, including fences, patios, and retaining walls. Bobby handles the documentation and coordinates with the city so you don't have to navigate it alone." },
      { question: "Can you build a patio on a waterfront lot near Spa Creek or the Severn River?", answer: "Absolutely. Waterfront lots require extra attention to drainage, soil conditions, and sometimes stormwater management plans. We've built hardscape and patios on waterfront properties throughout Annapolis and know exactly what the county requires." },
      { question: "What's the most popular outdoor project in Annapolis?", answer: "Hardscaping — patios, walkways, and retaining walls. Annapolis homeowners want usable outdoor living space, and with the compact yards common in neighborhoods like Eastport and West Annapolis, a well-designed patio makes the most of every square foot." },
      { question: "How long does a typical patio project take in Annapolis?", answer: "Most patio and hardscaping projects in Annapolis take 5–10 working days depending on size and complexity. Permitting can add 1–2 weeks upfront. We give you a firm timeline before any work begins." },
    ],
  },
  {
    name: "Arnold",
    slug: "arnold",
    county: "Anne Arundel County",
    nearby: ["annapolis", "severna-park", "pasadena", "crownsville", "riviera-beach"],
    headline: "Outdoor Construction on the Broadneck Peninsula",
    subheadline: "Arnold sits between the Magothy and Severn Rivers on the Broadneck Peninsula — one of Anne Arundel County's most desirable neighborhoods. Bobby's crew builds decks, patios, and outdoor living spaces designed for the area's larger lots and waterfront lifestyle.",
    localDescription: "Arnold is a quiet, affluent community on the Broadneck Peninsula with waterfront access along both the Magothy and Severn Rivers. Homes range from $485K ranches to $4M+ waterfront estates. The area is known for mature tree canopy, larger lots, and water-privileged communities like Cape St. Claire and St. Margaret's. Many Arnold homeowners invest in premium outdoor living spaces — composite decks, full patio setups, and privacy fencing that matches the neighborhood's character.",
    topServices: ["Decks", "Hardscaping", "Fencing", "Gravel Pads & Concrete Foundations"],
    localAngle: "With median home values over $556,000 and many lots backing up to water or wooded areas, Arnold homeowners expect craftsmanship that matches their investment. Bobby's crew builds with materials and techniques suited to the Broadneck's river-adjacent soil and the salt air that comes off the Chesapeake.",
    permitNote: "Arnold falls under Anne Arundel County permitting. Decks, fences, retaining walls, and accessory structures all require building permits through the county's Inspections and Permits department. Some water-privileged communities like Cape St. Claire have additional HOA architectural guidelines.",
    faqs: [
      { question: "Do Arnold's waterfront communities have special rules for decks and fences?", answer: "Some do. Cape St. Claire and other water-privileged communities have HOA guidelines for exterior modifications. We check your community's requirements before starting and make sure everything is approved before we build." },
      { question: "Can you work on properties with steep slopes toward the Magothy or Severn River?", answer: "Yes. Sloped lots are common on the Broadneck. We handle grading, retaining walls, and tiered patios designed for sloped terrain. Proper drainage is built into every project." },
      { question: "What deck materials hold up best near the water in Arnold?", answer: "We recommend composite decking for properties near the rivers or Bay. It handles salt air, humidity, and UV exposure far better than pressure-treated wood, and it won't need staining or sealing every year." },
      { question: "How much does a typical deck project cost in Arnold?", answer: "Every project is different, but we provide free on-site estimates so you get an accurate price based on your specific lot, materials, and scope — no ballpark guesses." },
    ],
  },
  {
    name: "Pasadena",
    slug: "pasadena",
    county: "Anne Arundel County",
    nearby: ["arnold", "glen-burnie", "riviera-beach", "severna-park", "linthicum-heights"],
    headline: "Contractor Services Along the Lake Shore Corridor",
    subheadline: "Pasadena stretches from the Magothy River down through Lake Shore to the Chesapeake Bay — a mix of waterfront communities, established neighborhoods, and growing subdivisions. Bobby's crew serves all of it.",
    localDescription: "Pasadena is one of the larger communities in Anne Arundel County, running from the Mountain Road corridor through Lake Shore down to Bodkin Point. The area has a wide range of housing — from 1950s ranches and Cape Cods to newer construction in developments off Tick Neck Road and Fort Smallwood Road. Many properties are on tighter lots than areas like Arnold or Severna Park, which makes maximizing outdoor space a priority. Waterfront and water-access communities line the Magothy River, Bodkin Creek, and the Bay.",
    topServices: ["Driveway Installation", "Fencing", "Gravel Pads & Concrete Foundations", "Decks"],
    localAngle: "Pasadena's older neighborhoods often have original driveways, aging fences, and yards that were never properly graded. Bobby's crew handles full tear-out and replacement — driveways, walkways, fencing — with proper base preparation and drainage that holds up through Maryland's freeze-thaw cycles.",
    permitNote: "Standard Anne Arundel County permits required for decks, fences, sheds, and driveways. Properties in flood zones near the Magothy or Bodkin Creek may require additional floodplain review. Always check whether your neighborhood has covenant restrictions before starting a project.",
    faqs: [
      { question: "My driveway in Pasadena is crumbling — can you replace the whole thing?", answer: "Yes. We tear out the old surface, re-grade the base, and install a new driveway — asphalt, concrete, or pavers depending on your preference and budget. Proper base prep is critical in Pasadena where a lot of the older driveways were built on inadequate foundations." },
      { question: "Do I need a permit to replace my fence in Pasadena?", answer: "In Anne Arundel County, fences over 6.5 feet require a permit. Even for standard fences, your property may have setback requirements or covenant restrictions. We handle the research and filing for you." },
      { question: "Can you build a gravel pad for my shed on a smaller Pasadena lot?", answer: "Absolutely. Tight lots are common in Pasadena and we build pads that maximize your usable space while meeting setback requirements. Proper drainage is especially important on compact lots." },
      { question: "How do I know if my Pasadena property is in a flood zone?", answer: "We can check this during your free estimate visit. Properties near the Magothy, Bodkin Creek, or the Bay may have floodplain restrictions that affect what and where we can build." },
    ],
  },
  {
    name: "Severna Park",
    slug: "severna-park",
    county: "Anne Arundel County",
    nearby: ["arnold", "annapolis", "pasadena", "crownsville", "millersville"],
    headline: "Premium Outdoor Living for Severna Park Families",
    subheadline: "Severna Park is one of Anne Arundel County's most family-oriented and affluent communities. Bobby builds outdoor spaces here that match the neighborhood — high-quality materials, clean design, and craftsmanship that adds real value to your home.",
    localDescription: "Severna Park is a tight-knit suburban community with excellent schools, mature tree-lined streets, and generous lot sizes. With a median household income over $150,000 and home values averaging $556,000+, homeowners here invest in their properties. The area sits between the Severn River and Magothy River, giving many neighborhoods that Chesapeake-adjacent feel. Popular neighborhoods include Olde Severna Park, Benfield, Shipley's Choice, and the communities along B&A Trail.",
    topServices: ["Decks", "Hardscaping", "Stamped Concrete", "Fencing"],
    localAngle: "Severna Park homeowners are discerning — they expect outdoor spaces that look as good as the rest of their home. Bobby's crew uses premium materials and techniques because that's what this community deserves. Many projects here are full backyard transformations: composite deck, paver patio, and professional landscaping borders done as a single coordinated project.",
    permitNote: "Anne Arundel County permits apply. Several Severna Park neighborhoods — Shipley's Choice, Chartridge, and others — have active HOAs with architectural review committees. If your neighborhood has covenants, get your HOA's approval before starting, or let us help you navigate the process.",
    faqs: [
      { question: "Does my Severna Park HOA need to approve a new deck or fence?", answer: "Many Severna Park neighborhoods have HOAs with architectural review requirements — Shipley's Choice, Chartridge, and Benfield among them. We're familiar with the process and can help you prepare the application with the drawings and material specs your HOA needs." },
      { question: "What's the best patio material for Severna Park homes?", answer: "We see a lot of demand for natural stone pavers and stamped concrete in Severna Park. Both hold up well in Maryland weather and offer the premium look that matches the neighborhood. We'll show you samples during your estimate so you can compare options in person." },
      { question: "Can you build a deck that connects to an existing patio?", answer: "Yes — this is one of the most popular project types in Severna Park. We design the transition between deck and patio so it flows naturally, with proper grading and drainage at the junction." },
      { question: "How far in advance should I book a project in Severna Park?", answer: "Spring and early summer are our busiest seasons. We recommend reaching out 4–6 weeks before you want work to start. We'll lock in your date at the time of approval." },
    ],
  },
  {
    name: "Crofton",
    slug: "crofton",
    county: "Anne Arundel County",
    nearby: ["odenton", "gambrills", "millersville", "severn"],
    headline: "Outdoor Construction That Meets Crofton's Standards",
    subheadline: "Crofton is a planned community with active HOAs and covenant requirements across most neighborhoods. Bobby's crew knows how to build beautiful outdoor spaces that also pass architectural review — no surprises, no rework.",
    localDescription: "Crofton was built as a planned community in the 1960s and today is one of Anne Arundel County's most popular suburban areas. Most neighborhoods fall under the Crofton Special Benefit District with active HOAs, covenant restrictions, and architectural review committees that must approve exterior modifications like decks, fences, and patios. The community has consistent lot sizes, established landscaping, and a strong neighborhood identity. Bobby has worked extensively in Crofton Village, the Knolls, Courts of Crofton, and surrounding sections.",
    topServices: ["Decks", "Fencing", "Stamped Concrete", "Hardscaping"],
    localAngle: "Building in Crofton means navigating HOA rules. Bobby's crew handles this routinely — we know what Crofton's covenant committees typically approve, what materials and heights are allowed, and how to prepare the drawings and specs the review process requires. That saves you time and avoids costly rework.",
    permitNote: "In addition to Anne Arundel County building permits, most Crofton homes require HOA approval through an Architectural Design Review Application before starting exterior work. Contact Crofton Town Hall at 410-721-2301 or check your covenants by street address at cityofcrofton.org to find your specific requirements.",
    faqs: [
      { question: "Do I need HOA approval for a new deck or fence in Crofton?", answer: "Almost certainly yes. Most Crofton neighborhoods require an Architectural Design Review Application for exterior modifications. We prepare the required drawings and material specifications as part of our estimate process." },
      { question: "What fence styles does Crofton typically approve?", answer: "It varies by section, but most Crofton HOAs approve wood privacy fences (6 feet max) and aluminum/vinyl fencing. Chain link is typically restricted in front and side yards. We'll check your specific covenant before recommending materials." },
      { question: "Can you build a stamped concrete patio in a Crofton backyard?", answer: "Yes — stamped concrete is popular in Crofton because it gives you the look of natural stone without exceeding typical HOA height and material restrictions. We've done dozens of patio projects across Crofton's different sections." },
      { question: "How long does it take to get HOA approval in Crofton?", answer: "Typically 2–4 weeks from application submission. We recommend starting the approval process early so we can have your project scheduled and ready to go as soon as you get the green light." },
    ],
  },
  {
    name: "Millersville",
    slug: "millersville",
    county: "Anne Arundel County",
    nearby: ["crofton", "severn", "odenton", "gambrills", "annapolis"],
    headline: "Your Neighbor in Millersville — Bobby's Home Base",
    subheadline: "Millersville is where Backyard Bobby's calls home. This is our community, our neighbors, and where we've completed more projects than anywhere else. When you hire Bobby, you're hiring local.",
    localDescription: "Millersville is a rural-to-suburban community in central Anne Arundel County with larger lots, horse properties, and a mix of older homes and newer construction. It sits at the crossroads of Route 3 and Veterans Highway, giving it easy access to the rest of the county. Because Millersville is Bobby's home base, the crew knows the area's soil conditions, drainage patterns, and grading challenges better than anywhere. Many properties here sit on 1–5 acre lots with room for detached structures, gravel pads, ADUs, and full outdoor living setups.",
    topServices: ["Gravel Pads & Concrete Foundations", "Excavation & Demolition", "Decks", "Accessory Dwelling Units"],
    localAngle: "This is home. Bobby lives in Millersville and has built for dozens of neighbors in the community. The larger lots here are perfect for gravel pads, shed foundations, and ADUs — and Bobby's equipment is minutes away, which means faster mobilization and lower costs for Millersville projects.",
    permitNote: "Millersville falls under Anne Arundel County permitting. Many properties are on well and septic, which affects where structures can be placed. Setbacks from septic systems and wells must be maintained. Bobby's crew checks all of this during the free estimate visit.",
    faqs: [
      { question: "Does being in Millersville mean faster service?", answer: "Honestly, yes. Bobby's equipment and crew are based right here in Millersville. Mobilization is faster, site visits are easier to schedule, and if anything comes up during your project, Bobby can be there in minutes." },
      { question: "My Millersville property has well and septic — does that affect where you can build?", answer: "It does. Structures need to maintain setbacks from your well and septic system. We check your property's as-built and septic layout during the estimate to make sure your project is positioned correctly." },
      { question: "Can you build an ADU on a larger Millersville lot?", answer: "Millersville's larger lots are ideal for accessory dwelling units. We handle everything from excavation and foundation through framing, utilities, and finish — including all permitting coordination with the county." },
      { question: "What's the most common project you do in Millersville?", answer: "Gravel pads and shed foundations — by a wide margin. The larger properties here are perfect for detached structures, and Bobby has built more gravel pads in Millersville than anywhere else in the county." },
    ],
  },
  {
    name: "Severn",
    slug: "severn",
    county: "Anne Arundel County",
    nearby: ["odenton", "millersville", "linthicum-heights", "glen-burnie", "hanover"],
    headline: "Outdoor Construction for Severn's Growing Community",
    subheadline: "Severn is a rapidly growing community where older established homes meet new development. Bobby's crew handles everything from grading and drainage fixes on older properties to fresh outdoor builds on new construction.",
    localDescription: "Severn is a large census-designated place stretching from the Baltimore-Washington corridor through suburban neighborhoods and into semi-rural areas. It's home to a mix of 1960s–80s ranches and split-levels alongside newer townhome and single-family developments. Many of the older properties have original grading and drainage issues that need addressing before or during outdoor construction. Proximity to Fort Meade and NSA brings steady population growth and housing demand.",
    topServices: ["Driveway Installation", "Fencing", "Gravel Pads & Concrete Foundations", "Excavation & Demolition"],
    localAngle: "Older Severn properties often have decades-old grading that sends water toward the foundation. Bobby's crew doesn't just build your patio or driveway — we fix the underlying drainage problem first. New construction homes in Severn frequently need outdoor upgrades beyond the builder-grade basics: better fencing, a real patio, and a proper gravel pad for that shed.",
    permitNote: "Anne Arundel County permits required. Severn's mix of older and newer developments means some neighborhoods have HOA restrictions while others don't. Always verify your property's covenants before starting work.",
    faqs: [
      { question: "My Severn property has poor drainage — can you fix that during a patio project?", answer: "Absolutely. We see this constantly in Severn's older neighborhoods. We re-grade the area, install proper drainage, and then build your patio on a solid, well-drained base. Fixing the drainage and building the patio together is more cost-effective than doing them separately." },
      { question: "Can you build on a newly constructed home in Severn?", answer: "Yes. New construction in Severn often comes with minimal outdoor finishes. We upgrade builder-grade fencing, add proper patios, install gravel pads for sheds, and handle all the outdoor work the builder left out." },
      { question: "Do I need a permit to replace my driveway in Severn?", answer: "Driveway replacements in Anne Arundel County typically require a permit if you're changing the footprint or grading. If you're replacing in-kind, you may not need one. We'll confirm during your estimate." },
      { question: "How much does a gravel pad for a shed cost in Severn?", answer: "It depends on the pad size, material depth, and site conditions. We provide free, detailed estimates on every project so you know exactly what you're paying for before we start." },
    ],
  },
  {
    name: "Odenton",
    slug: "odenton",
    county: "Anne Arundel County",
    nearby: ["crofton", "severn", "gambrills", "millersville"],
    headline: "Serving Odenton — Anne Arundel's Fastest-Growing Community",
    subheadline: "Odenton's growth around Fort Meade and the MARC station has brought thousands of new homeowners who need quality outdoor construction. Bobby's crew has been building here since before the boom.",
    localDescription: "Odenton has transformed from a small town into one of Maryland's fastest-growing communities, driven by Fort Meade, NSA, and the Odenton Town Center development. The area is a mix of new master-planned communities, established suburban neighborhoods, and pockets of rural land. New developments like Piney Orchard, Odenton Town Center, and the neighborhoods around the MARC station bring homeowners who want to personalize their outdoor spaces beyond what the builder provided. Older Odenton properties near Route 175 often need modernized outdoor spaces.",
    topServices: ["Fencing", "Decks", "Gravel Pads & Concrete Foundations", "Driveway Installation"],
    localAngle: "New construction dominates Odenton, but builder-grade outdoor finishes rarely impress. Bobby upgrades Odenton properties from basic to built-right — swapping out cheap builder fencing for real wood or vinyl privacy fencing, replacing stamped-out concrete stoops with full patios, and adding the sheds and structures that new homeowners need.",
    permitNote: "Anne Arundel County permits required. Many Odenton neighborhoods — Piney Orchard, Seven Oaks, and others — have active HOAs that require architectural approval for exterior modifications. The Odenton Town Center overlay may have additional design standards for properties within its boundary.",
    faqs: [
      { question: "Can you upgrade the builder-grade fence on my new Odenton home?", answer: "This is one of our most common Odenton requests. We remove the builder's fence and install quality wood, vinyl, or aluminum fencing that actually looks good and lasts. Most builder fences are the bare minimum — you deserve better." },
      { question: "Does Piney Orchard's HOA need to approve a new deck?", answer: "Yes. Piney Orchard and most newer Odenton communities have architectural review processes. We prepare the application materials — drawings, material specs, and site plans — as part of our estimate." },
      { question: "Can you build a patio on a new-construction lot in Odenton?", answer: "Absolutely. New construction lots in Odenton are usually well-graded, which makes them ideal for patio installation. We can often get started faster on newer lots because the site prep is minimal." },
      { question: "How far out are you booking in Odenton?", answer: "Odenton is close to our Millersville base, so we're in the area frequently. Typically 2–4 weeks out, though spring and summer book faster." },
    ],
  },
  {
    name: "Edgewater",
    slug: "edgewater",
    county: "Anne Arundel County",
    nearby: ["annapolis", "riva", "shady-side", "parole", "arnold"],
    headline: "Outdoor Construction Along the South River",
    subheadline: "Edgewater wraps around the South River with waterfront properties, sloped lots, and Coastal Plain soil that require a contractor who understands the terrain. Bobby's crew builds with drainage and erosion in mind on every project.",
    localDescription: "Edgewater is a South River waterfront community in southern Anne Arundel County. The South River watershed drains 66 square miles of land, and Edgewater sits right in the middle of it — meaning water, erosion, and drainage are constant factors in outdoor construction. The terrain is characterized by steep slopes and rolling hills despite being in the Coastal Plain, and many properties have challenging grading. Neighborhoods along Mayo Road, the South River, and Beards Creek combine waterfront living with rural character.",
    topServices: ["Hardscaping", "Excavation & Demolition", "Decks", "Fencing"],
    localAngle: "Every Edgewater project Bobby builds starts with a drainage assessment. The South River watershed's terrain means water moves aggressively across properties during rain events. We engineer retaining walls, patios, and walkways with drainage channels, proper slope, and compacted bases that prevent erosion and pooling.",
    permitNote: "Anne Arundel County permits apply. Properties near the South River and Beards Creek may fall within the Critical Area (1,000-foot buffer from tidal waters), which triggers additional environmental review. Stormwater management plans may be required for work near the waterfront.",
    faqs: [
      { question: "My Edgewater lot slopes toward the South River — can you still build a patio?", answer: "Yes. Sloped lots are our specialty in Edgewater. We use retaining walls, tiered patio designs, and proper grading to create level outdoor living space on even the steepest lots. Drainage is engineered into the design from day one." },
      { question: "Is my property in the Critical Area?", answer: "If you're within 1,000 feet of the South River, Beards Creek, or another tidal waterway, your property may be in the Critical Area buffer. This requires additional environmental review for construction projects. We check this during your free estimate." },
      { question: "What causes the erosion problems on Edgewater properties?", answer: "The South River watershed has steep slopes and clay-heavy Coastal Plain soil that doesn't absorb water quickly. When it rains, water runs fast across the surface and erodes bare soil. Proper hardscaping with drainage channels and retaining walls is the permanent fix." },
      { question: "Can you build a deck on a waterfront property in Edgewater?", answer: "Absolutely. We build elevated decks on waterfront lots that account for slope, soil conditions, and any Critical Area setbacks. Composite materials are recommended for salt-air exposure." },
    ],
  },
  {
    name: "Gambrills",
    slug: "gambrills",
    county: "Anne Arundel County",
    nearby: ["crofton", "odenton", "millersville", "severn", "crownsville"],
    headline: "Quality Outdoor Construction on Gambrills' Spacious Lots",
    subheadline: "Gambrills offers the space that the rest of Anne Arundel County wishes it had — larger lots, rural character, and room to build. Bobby's crew takes full advantage of that space with structures and outdoor areas built to last.",
    localDescription: "Gambrills is a quiet, rural-suburban community tucked between Crofton, Odenton, and Millersville. The area is known for larger lots, open space, and a country feel that's increasingly rare this close to Baltimore and DC. Properties in Gambrills often sit on 1–3+ acres with room for detached garages, workshops, ADUs, large decks, and full outdoor entertaining areas. The community has a mix of older farmhouse-style properties and newer executive homes.",
    topServices: ["Gravel Pads & Concrete Foundations", "Accessory Dwelling Units", "Excavation & Demolition", "Decks"],
    localAngle: "Gambrills lots give Bobby room to work. Where tighter communities limit what you can build, Gambrills properties allow for full-scale projects — large gravel pads for oversized structures, concrete slab foundations for garages, ADUs with room to breathe, and outdoor living areas that don't feel cramped.",
    permitNote: "Anne Arundel County permits required. Many Gambrills properties are on well and septic systems, which dictate setbacks for new structures. County zoning in Gambrills can vary — some areas are zoned residential, others agricultural. We verify zoning and setbacks before providing your estimate.",
    faqs: [
      { question: "Can I build a detached garage or workshop on my Gambrills property?", answer: "Most Gambrills lots have the space and zoning for detached structures. We handle the concrete foundation or gravel pad and coordinate with the county on permits and setbacks, especially around well and septic systems." },
      { question: "Does well and septic limit where I can build in Gambrills?", answer: "It affects placement, not whether you can build. New structures must maintain setbacks from your well and septic field. We review your property's layout during the estimate to find the best location." },
      { question: "Is an ADU allowed on Gambrills properties?", answer: "Anne Arundel County permits ADUs under certain conditions. Gambrills' larger lots often meet the size requirements easily. We handle the permitting research and construction from foundation to finish." },
      { question: "How much land do I need for a large gravel pad?", answer: "For a typical 12x16 shed pad, you need the pad footprint plus setback clearances. Gambrills lots almost always have plenty of room. For larger structures like garages, we'll measure setbacks during your free estimate." },
    ],
  },
  {
    name: "Crownsville",
    slug: "crownsville",
    county: "Anne Arundel County",
    nearby: ["annapolis", "arnold", "severna-park", "gambrills", "millersville"],
    headline: "Building on Crownsville's Wooded, Rolling Terrain",
    subheadline: "Crownsville's heavily wooded lots and rolling terrain make outdoor construction a different challenge than flat suburban neighborhoods. Bobby's crew has the equipment and experience to build right in these conditions.",
    localDescription: "Crownsville is a wooded, semi-rural community between Annapolis and Millersville. The county preserved a 546-acre forested parcel here to maintain the area's natural character. Properties are typically set back from the road on wooded lots with mature hardwood canopy, rolling terrain, and significant tree root systems. Building in Crownsville often requires selective tree removal, stump grinding, and careful grading before construction can begin. The area's soil tends toward clay-heavy Coastal Plain composition under a layer of organic forest floor.",
    topServices: ["Excavation & Demolition", "Gravel Pads & Concrete Foundations", "Decks", "Hardscaping"],
    localAngle: "Crownsville properties need site work before the actual build. Bobby's crew handles tree clearing, stump removal, grading, and root system management before laying a single paver or pouring any concrete. Skipping this step is how other contractors end up with heaving patios and sinking foundations — we don't skip it.",
    permitNote: "Anne Arundel County permits apply. Tree removal may require additional county approval, especially for properties in designated forest conservation areas. Crownsville's wooded character means the county pays closer attention to clearing and grading here than in already-developed neighborhoods.",
    faqs: [
      { question: "Do I need to remove trees before building a patio in Crownsville?", answer: "Often yes. Crownsville lots are heavily wooded and tree roots can undermine hardscaping if they're not addressed. We handle selective removal, stump grinding, and root management as part of the project — not as a surprise extra." },
      { question: "Does the county restrict tree removal in Crownsville?", answer: "Some areas have forest conservation requirements that limit how many trees you can remove. We check your property's status and work within the guidelines, recommending selective clearing that preserves the natural feel while creating the space you need." },
      { question: "Can you build on a sloped, wooded lot in Crownsville?", answer: "That's most of Crownsville. We use retaining walls, tiered construction, and strategic grading to work with the slope rather than fighting it. The result is an outdoor space that looks natural to the property, not forced." },
      { question: "What kind of equipment do you bring for Crownsville site work?", answer: "Mini excavators, Toro Dingos, and compact equipment that can navigate wooded lots and tight access points. We've worked on properties with narrow driveways and dense tree cover throughout Crownsville." },
    ],
  },
  {
    name: "Shady Side",
    slug: "shady-side",
    county: "Anne Arundel County",
    nearby: ["edgewater", "riva", "annapolis", "parole"],
    headline: "Serving Shady Side — Where Other Contractors Won't Go",
    subheadline: "Shady Side sits at the tip of the peninsula where the West River meets the Chesapeake Bay. It's remote, waterfront, and underserved by contractors. Bobby makes the drive because every homeowner here deserves quality work.",
    localDescription: "Shady Side is a small, tight-knit waterfront community at the southern tip of the peninsula between the West River and Chesapeake Bay. It's one of the most remote communities in Anne Arundel County — a characteristic that means many contractors don't bother serving it. Properties are a mix of year-round homes and seasonal waterfront cottages, many on older foundations with yards exposed to bay winds and tidal influence. The community has a waterman's heritage and a relaxed, rural feel unlike anywhere else in the county.",
    topServices: ["Fencing", "Decks", "Hardscaping", "Gravel Pads & Concrete Foundations"],
    localAngle: "Most contractors don't make the drive to Shady Side — Bobby does. Being based in Millersville means Shady Side is within his service radius, and the community deserves the same quality work as Annapolis or Severna Park. Waterfront conditions here mean salt-resistant materials and drainage-first construction are non-negotiable.",
    permitNote: "Anne Arundel County permits apply. Nearly all Shady Side properties are within the Critical Area (1,000-foot buffer from tidal waters) due to the community's narrow peninsula geography. Most outdoor construction projects here will require Critical Area review and possibly a buffer management plan.",
    faqs: [
      { question: "Do you actually serve Shady Side?", answer: "Yes. We know a lot of Shady Side homeowners have been told no by other contractors. Bobby's based in Millersville — Shady Side is within our regular service area, and we treat every project here with the same attention as any other community." },
      { question: "Is everything in Shady Side in the Critical Area?", answer: "Practically, yes. The peninsula is narrow enough that most properties fall within the 1,000-foot tidal buffer. This means additional review for construction projects, but we handle the paperwork and coordination with the county." },
      { question: "What materials hold up to bay winds and salt air?", answer: "We recommend composite decking, vinyl or aluminum fencing, and concrete or natural stone for hardscaping. Pressure-treated wood deteriorates much faster in salt air environments. We'll walk you through material options during your estimate." },
      { question: "Can you work on an older waterfront cottage in Shady Side?", answer: "Absolutely. Many Shady Side properties are older cottages that need modern outdoor improvements. We work with existing structures and foundations, reinforcing where needed and building new where it makes sense." },
    ],
  },
  {
    name: "Linthicum Heights",
    slug: "linthicum-heights",
    county: "Anne Arundel County",
    nearby: ["glen-burnie", "severn", "pasadena", "hanover"],
    headline: "Outdoor Construction in Historic Linthicum Heights",
    subheadline: "Linthicum Heights is a historic community near BWI with charming older homes, compact lots, and a neighborhood character worth preserving. Bobby builds outdoor spaces that complement the area's established aesthetic.",
    localDescription: "Linthicum Heights is one of Anne Arundel County's oldest communities, founded in 1908 with architecture spanning Bungalow, American Foursquare, Colonial Revival, and Tudor Revival styles. Its historic district is listed on the National Register of Historic Places. Lots are typically compact — tighter than suburban developments in Crofton or Severna Park — and the neighborhood has a walkable, small-town feel. Proximity to BWI Airport means noise is a factor, and some homeowners invest in privacy fencing and outdoor sound buffering. The community sits along the light rail line, connecting it to Baltimore and BWI.",
    topServices: ["Fencing", "Driveway Installation", "Hardscaping", "Stamped Concrete"],
    localAngle: "Linthicum's compact lots and historic character require a thoughtful approach. Bobby's crew builds on tight properties without damaging neighboring yards, works around mature landscaping, and selects materials that match the community's established aesthetic. No cookie-cutter solutions here.",
    permitNote: "Anne Arundel County permits apply. Properties within the Linthicum Heights Historic District may have additional design review requirements for exterior modifications. Check with the county's historic preservation office if your property is within the district boundaries.",
    faqs: [
      { question: "Can you work on a tight lot in Linthicum Heights without damaging my neighbor's property?", answer: "We do this constantly in Linthicum. Compact equipment, careful staging, and clear communication with both you and your neighbors. We've never damaged a neighboring property and we plan access and staging before we start." },
      { question: "Does the historic district affect what I can build?", answer: "If your property is within the Linthicum Heights Historic District, exterior modifications may need to be consistent with the community's architectural character. The county can provide guidance, and Bobby's crew works within these guidelines." },
      { question: "Can you replace a driveway on a small Linthicum lot?", answer: "Yes. Many Linthicum driveways are original and showing their age. We tear out, re-grade, and replace with new concrete, asphalt, or pavers — working within the tight footprint and maintaining access for you throughout the project." },
      { question: "Does BWI airport affect outdoor construction in Linthicum?", answer: "Not the construction itself, but some homeowners near the airport invest in taller privacy fencing and denser landscape borders for noise buffering. We can recommend materials and designs that help." },
    ],
  },
  {
    name: "Riviera Beach",
    slug: "riviera-beach",
    county: "Anne Arundel County",
    nearby: ["pasadena", "arnold", "glen-burnie"],
    headline: "Waterfront-Ready Construction in Riviera Beach",
    subheadline: "Riviera Beach sits right on the Chesapeake Bay with waterfront and water-access properties that need outdoor construction built for coastal conditions. Bobby's crew uses the right materials and techniques for Bay-adjacent building.",
    localDescription: "Riviera Beach is a waterfront community in northeastern Anne Arundel County where the Patapsco River meets the Chesapeake Bay. Many properties have direct water access or are within walking distance of community beaches and marinas. The area has a mix of post-war cottages and updated homes, with yards that face direct Bay exposure — including salt spray, wind, and occasional tidal flooding in low-lying areas. Outdoor construction here must account for these conditions or it won't last.",
    topServices: ["Decks", "Fencing", "Hardscaping", "Driveway Installation"],
    localAngle: "Bay-adjacent construction is different. Bobby's crew selects materials rated for salt-air exposure, builds with drainage margins for storm surge, and uses hardware and fasteners that won't corrode in two years. Standard inland construction practices fail quickly in Riviera Beach — we build for the actual conditions.",
    permitNote: "Anne Arundel County permits apply. Waterfront properties may fall within the Critical Area and require additional review. Low-lying properties should verify flood zone status, as this affects foundation requirements and insurance.",
    faqs: [
      { question: "What decking material works best near the Bay in Riviera Beach?", answer: "Composite decking with stainless steel or coated fasteners. Traditional pressure-treated lumber breaks down rapidly in salt air. Composite costs more upfront but lasts significantly longer in waterfront conditions and needs almost zero maintenance." },
      { question: "Can you build a patio on a flood-prone Riviera Beach lot?", answer: "Yes, but the design needs to account for water. Permeable pavers, elevated patio designs, and proper grading that channels water away from your foundation are all options we use on low-lying Riviera Beach properties." },
      { question: "My fence is rotting from the salt air — what should I replace it with?", answer: "Vinyl or aluminum. Wood fences near the Bay typically need replacement every 5–8 years. Vinyl and aluminum are salt-resistant and last 20+ years with minimal maintenance." },
      { question: "Are there special permits for building near the water?", answer: "Properties in the Critical Area (within 1,000 feet of tidal water) require additional environmental review. If your project is close to the shoreline, there may be Army Corps requirements too. We check all of this during your estimate." },
    ],
  },
  {
    name: "Riva",
    slug: "riva",
    county: "Anne Arundel County",
    nearby: ["annapolis", "edgewater", "shady-side", "parole"],
    headline: "Outdoor Living Upgrades in Waterfront Riva",
    subheadline: "Riva blends waterfront estates along Beards Creek with inland neighborhoods full of ranches and colonials. Bobby's crew builds outdoor spaces tailored to both — from waterfront decks to suburban patio transformations.",
    localDescription: "Riva is a residential community just south of Annapolis, centered along Riva Road (MD-214) and Beards Creek. The area has an eclectic mix of housing — ranches, colonials, split-levels, and waterfront estates. Inland homes typically range from $400K–$600K, while waterfront properties along Beards Creek and the South River exceed $1M and often include private docks. Neighborhoods like Berkshire, Stone Ridge, and Annapolis Landing have active HOAs. Local landmarks include Mike's Crab House along the marina and Riva Gardens & Farm Market.",
    topServices: ["Decks", "Hardscaping", "Stamped Concrete", "Fencing"],
    localAngle: "Riva's variety means every project is different. A waterfront estate on Beards Creek needs a different approach than a ranch in Stone Ridge. Bobby's crew tailors materials, design, and drainage strategy to each property's specific conditions — not a one-size-fits-all template.",
    permitNote: "Anne Arundel County permits required. Several Riva neighborhoods have HOA covenants — Berkshire, Stone Ridge, and Annapolis Landing among them. Waterfront properties near Beards Creek may fall in the Critical Area and require additional review.",
    faqs: [
      { question: "Does my Riva HOA need to approve a new patio?", answer: "If you're in Berkshire, Stone Ridge, Annapolis Landing, or another covenant community, yes — most require architectural approval for exterior modifications. We'll check your specific community's requirements during the estimate." },
      { question: "Can you build a deck on a waterfront lot along Beards Creek?", answer: "Yes. Waterfront decks are one of our specialties. We use composite materials, corrosion-resistant hardware, and elevated designs that work with the terrain and account for proximity to tidal water." },
      { question: "What's the most popular backyard project in Riva?", answer: "Patios and deck builds. Riva homeowners want usable outdoor living space for entertaining, and the area's tree-lined lots provide natural privacy that makes outdoor spaces feel like outdoor rooms." },
      { question: "How do you handle drainage on Riva properties near the creek?", answer: "Properties near Beards Creek have high water tables and runoff concerns. We engineer drainage into every hardscape project — grading, French drains, and permeable materials where appropriate." },
    ],
  },
  {
    name: "Herald Harbor",
    slug: "herald-harbor",
    county: "Anne Arundel County",
    nearby: ["crownsville", "annapolis", "arnold", "severna-park"],
    headline: "Outdoor Construction in Herald Harbor's Unique Waterfront Community",
    subheadline: "Herald Harbor is a small, private waterfront community on the Severn River with narrow roads, wooded lots, and a character unlike anywhere else in the county. Bobby's compact equipment and local knowledge make him the right fit.",
    localDescription: "Herald Harbor is a small, secluded waterfront community on the Severn River, just north of Annapolis. It's a tight-knit enclave with narrow access roads, wooded lots, steep terrain down to the water, and a community beach and marina. Properties range from modest cottages to renovated waterfront homes. The community's character — quiet, wooded, and water-focused — attracts homeowners who want outdoor spaces that blend into the natural setting rather than dominate it.",
    topServices: ["Decks", "Hardscaping", "Fencing", "Excavation & Demolition"],
    localAngle: "Herald Harbor's narrow roads and tight access points stop a lot of contractors from even trying. Bobby's crew uses compact equipment — mini excavators, Toro Dingos, and small-footprint loaders — that navigate Herald Harbor's roads and wooded lots without tearing up the community.",
    permitNote: "Anne Arundel County permits apply. Herald Harbor's waterfront location means most properties are in the Critical Area. The community may have additional association rules regarding exterior modifications. Steep lots require careful equipment access planning.",
    faqs: [
      { question: "Can you get equipment into Herald Harbor's narrow roads?", answer: "Yes. We use compact equipment specifically suited for tight access — mini excavators, track loaders, and Toro Dingos. We've worked in Herald Harbor before and know how to navigate the community without causing damage to roads or neighboring properties." },
      { question: "My Herald Harbor lot is steep and wooded — is a patio possible?", answer: "Absolutely. Tiered retaining walls and level patio areas are the solution for Herald Harbor's terrain. We build into the slope to create usable outdoor space while preserving the natural look of the property." },
      { question: "Does Herald Harbor have its own rules about outdoor construction?", answer: "Herald Harbor has a community association that may have guidelines for exterior modifications. We recommend checking with your association board before starting, and we're happy to work within any community-specific requirements." },
      { question: "What kind of deck works best on a steep Herald Harbor lot?", answer: "Elevated composite decks with proper post-in-ground or helical pier foundations. The elevation works with the slope to give you level outdoor living space and often provides stunning Severn River views from above the tree canopy." },
    ],
  },
  {
    name: "Parole",
    slug: "parole",
    county: "Anne Arundel County",
    nearby: ["annapolis", "edgewater", "crownsville", "riva"],
    headline: "Outdoor Construction in Parole's Growing Town Center",
    subheadline: "Parole is where suburban meets commercial just west of Annapolis — a growing town center with townhome communities, single-family neighborhoods, and homeowners who want to make the most of their outdoor space.",
    localDescription: "Parole is a designated Town Center spanning nearly 1,500 acres just west of downtown Annapolis. The area has grown significantly since the 1980s, evolving from a rural crossroads into a shopping, dining, and residential hub. Housing ranges from townhome communities along Jennifer Road and Bestgate Road to single-family neighborhoods further from the commercial core. Many homes have smaller yards than communities further out, making smart outdoor design critical. Parole's location at the intersection of Routes 2 and 450 makes it one of the most accessible areas in the county.",
    topServices: ["Hardscaping", "Fencing", "Stamped Concrete", "Driveway Installation"],
    localAngle: "Parole's smaller lots and townhome communities require design that maximizes every square foot. Bobby's crew builds compact patios, privacy fencing, and outdoor living areas engineered for tighter spaces — without feeling cramped. In Parole, good design matters more than raw lot size.",
    permitNote: "Anne Arundel County permits apply. Parole's Town Center designation may apply additional design standards for some properties. Townhome communities throughout Parole typically have HOA requirements for exterior modifications.",
    faqs: [
      { question: "Can you build a patio behind a Parole townhome?", answer: "Yes. Townhome patios are one of our most common Parole projects. We design within the footprint allowed by your HOA and property lines, using materials and layouts that make a compact space feel much larger." },
      { question: "My Parole townhome has an HOA — do you deal with that?", answer: "We work with Parole HOAs regularly. We prepare the drawings and material specs your association needs for approval, and we build to whatever specifications they require." },
      { question: "Can you replace the driveway on my Parole townhome?", answer: "It depends on your HOA's rules — some townhome communities control driveway materials and appearance. We'll check your community's requirements and give you options that work within them." },
      { question: "Is there enough room for a fence on a small Parole lot?", answer: "Usually yes. Even on compact lots, privacy fencing can transform your outdoor space. We measure setbacks, check HOA height limits, and design a fence plan that gives you maximum privacy within the rules." },
    ],
  },
  {
    name: "Glen Burnie",
    slug: "glen-burnie",
    county: "Anne Arundel County",
    nearby: ["linthicum-heights", "pasadena", "severn", "hanover"],
    headline: "Honest Outdoor Construction in Glen Burnie",
    subheadline: "Glen Burnie is a working-class community with 73,000+ residents and some of the most established neighborhoods in Anne Arundel County. Bobby provides straightforward, quality outdoor construction — no upselling, no shortcuts.",
    localDescription: "Glen Burnie is the largest community in Anne Arundel County by population, stretching from Marley Station to Crain Highway with a wide range of neighborhoods. Many homes were built in the 1950s–1970s and feature original driveways, aging fences, and yards that need modernization. The community is diverse and practical — homeowners here want projects done right at fair prices. Glen Burnie's central location gives it excellent highway access via I-97 and Route 2, but also means many properties sit on busier streets where privacy fencing is a priority.",
    topServices: ["Driveway Installation", "Fencing", "Gravel Pads & Concrete Foundations", "Stamped Concrete"],
    localAngle: "Glen Burnie homeowners are practical — they want quality work at fair prices with no gimmicks. Bobby's crew delivers exactly that. Many Glen Burnie projects are replacements: crumbling driveways, rotting fences, and cracked walkways replaced with materials and workmanship that'll last decades, not years.",
    permitNote: "Anne Arundel County permits required for decks, fences over 6.5 feet, and accessory structures. Glen Burnie's established neighborhoods generally don't have HOAs, which means fewer restrictions but doesn't eliminate the need for county permits.",
    faqs: [
      { question: "How much does a driveway replacement cost in Glen Burnie?", answer: "Every driveway is different — size, material, condition of the base underneath, and access all affect the price. We provide free, detailed estimates so you know exactly what you're paying for. No ballpark guesses, no surprise costs." },
      { question: "My Glen Burnie property doesn't have an HOA — do I still need permits?", answer: "Yes. County building permits are still required for certain projects regardless of HOA status. Decks, fences over 6.5 feet, sheds over 200 square feet, and new driveways typically need permits. We handle the permitting for you." },
      { question: "Can you add a privacy fence along a busy road in Glen Burnie?", answer: "Absolutely. This is one of our most popular Glen Burnie projects. A solid wood or vinyl privacy fence along a busy road transforms your yard from exposed to private. We install with proper setbacks from the road and sidewalk." },
      { question: "Can you tear out an old concrete driveway?", answer: "Yes. Full tear-out and replacement is our standard approach for failing driveways. We remove the old concrete or asphalt, fix the grading and base underneath, and install your new surface on a proper foundation." },
    ],
  },
  {
    name: "Hanover",
    slug: "hanover",
    county: "Anne Arundel County",
    nearby: ["severn", "linthicum-heights", "odenton", "gambrills"],
    headline: "Upgrading Hanover's New Construction Outdoors",
    subheadline: "Hanover has exploded with new development around Arundel Mills and Maryland Live. Bobby upgrades builder-grade outdoor spaces into something you'll actually enjoy — premium materials, real design, and craftsmanship the builders skip.",
    localDescription: "Hanover is one of Anne Arundel County's newest and fastest-developing areas, anchored by the Arundel Mills mall complex — the largest single tourist destination in Maryland at 2.5+ million square feet. New residential development surrounds the commercial core, with master-planned communities, townhomes, and single-family homes that come with builder-grade outdoor finishes: basic concrete stoops, cheap fencing, and no-frills yards. Hanover sits at the intersection of MD-100 and MD-295 with excellent highway access to Baltimore, DC, and BWI.",
    topServices: ["Fencing", "Decks", "Stamped Concrete", "Gravel Pads & Concrete Foundations"],
    localAngle: "Hanover is new — but new construction outdoor finishes are universally disappointing. Bobby's crew replaces builder-grade fencing with real privacy fencing, swaps concrete stoops for full stamped-concrete patios, and adds the decks, sheds, and outdoor structures that transform a new house into a home.",
    permitNote: "Anne Arundel County permits required. Most Hanover developments have active HOAs with architectural review requirements. New construction communities may also have builder covenants that expire over time — check whether your community's original developer covenants are still in effect.",
    faqs: [
      { question: "Can I upgrade the builder fence on my Hanover home?", answer: "Absolutely — and you should. Builder fencing is the cheapest option available. We replace it with quality wood, vinyl, or aluminum privacy fencing that actually looks good and lasts. This is our most common Hanover project." },
      { question: "Does my Hanover HOA need to approve a deck or patio?", answer: "Almost certainly. New Hanover communities have active HOAs with architectural review. We prepare all the required materials — site plans, drawings, and material specs — as part of our proposal." },
      { question: "How soon after moving into a new Hanover home can I start outdoor projects?", answer: "We recommend waiting at least a few months for the ground to settle after new construction. The builders compact the soil during construction, but it needs time to stabilize. We'll assess readiness during your estimate." },
      { question: "Can you add a stamped concrete patio to a new construction home in Hanover?", answer: "Yes — this is one of the best investments you can make in a new Hanover home. The builder leaves you with a basic concrete stoop. We extend it into a full patio with stamped patterns and color that complement your home's style." },
    ],
  },
];

export const SERVICE_AREAS = [
  "Annapolis",
  "Arnold",
  "Pasadena",
  "Severna Park",
  "Crofton",
  "Millersville",
  "Severn",
  "Odenton",
  "Edgewater",
  "Gambrills",
  "Crownsville",
  "Shady Side",
  "Linthicum Heights",
  "Riviera Beach",
  "Riva",
  "Herald Harbor",
  "Parole",
  "Glen Burnie",
  "Hanover",
] as const;

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Areas", href: "/areas" },
  { label: "Gallery", href: "/gallery" },
  { label: "About", href: "/about" },
  { label: "Blog", href: "/blog" },
  { label: "Financing", href: "/financing" },
  { label: "Contact", href: "/contact" },
] as const;

export const PRIMARY_SERVICES = [
  {
    title: "Stamped Concrete",
    slug: "stamped-concrete",
    shortDesc: "High-end concrete finishes at a fraction of stone costs.",
    icon: "Stamp",
    image: "/images/stamped-concrete-driveway-decorative-01.webp",
  },
  {
    title: "Hardscaping",
    slug: "hardscaping",
    shortDesc: "Patios, walkways, and retaining walls that transform your yard.",
    icon: "Landmark",
    image: "/images/paver-walkway-interlocking-bricks-01.jpeg",
  },
  {
    title: "Decks",
    slug: "decks",
    shortDesc: "Beautiful decks for outdoor entertaining year-round.",
    icon: "Fence",
    image: "/images/wood-deck-construction-01.webp",
  },
  {
    title: "Driveway Installation",
    slug: "driveway-installation",
    shortDesc: "Durable driveways built to last through Maryland weather.",
    icon: "CarFront",
    image: "/images/service-driveway-installation.png",
  },
  {
    title: "Fencing",
    slug: "fencing",
    shortDesc: "Privacy, security, and style for your yard.",
    icon: "Fence",
    image: "/images/service-fencing.png",
  },
  {
    title: "Gravel Pads & Concrete Foundations",
    slug: "gravel-pads-and-concrete-foundations",
    shortDesc: "Solid bases for sheds, garages, and outdoor structures.",
    icon: "Layers",
    image: "/images/gravel-pad-shed-foundation-01.jpeg",
  },
  {
    title: "Roofing",
    slug: "roofing",
    shortDesc: "Reliable roofing repairs and installations you can trust.",
    icon: "HardHat",
    image: "/images/roof-architectural-shingles-colonial.jpg",
  },
  {
    title: "Excavation & Demolition",
    slug: "excavation-and-demolition",
    shortDesc: "Professional site work to prepare your property right.",
    icon: "Construction",
    image: "/images/excavation-site-grading-backhoe-01.webp",
  },
  {
    title: "Accessory Dwelling Units",
    slug: "accessory-dwelling-units",
    shortDesc: "Custom ADUs that add living space and property value.",
    icon: "Home",
    image: "/images/service-accessory-dwelling-unit.png",
  },
] as const;

export const ADDITIONAL_SERVICES = [
  "Site Prep for Sheds",
  "Site Prep for Playgrounds",
  "Shed Kits",
  "Hauling",
  "Junk Removal & Debris Removal",
] as const;

export const ALL_SERVICES_FOR_FORM = [
  ...PRIMARY_SERVICES.map((s) => s.title),
  ...ADDITIONAL_SERVICES,
] as const;

export const TESTIMONIALS = [
  {
    name: "Mike R.",
    location: "Severna Park, MD",
    text: "Bobby's crew installed a stamped concrete patio and it looks incredible. They showed up on time every day and kept the yard clean. Couldn't be happier with the result.",
    service: "Stamped Concrete",
    rating: 5,
  },
  {
    name: "Sarah T.",
    location: "Annapolis, MD",
    text: "We needed a gravel pad for our new shed and the team had it done in two days. The drainage is perfect and the price was very fair. Highly recommend.",
    service: "Gravel Pads",
    rating: 5,
  },
  {
    name: "James & Linda P.",
    location: "Crofton, MD",
    text: "Our new deck is the best investment we've made in this house. The craftsmanship is top notch and Bobby walked us through every decision. Five stars.",
    service: "Decks",
    rating: 5,
  },
  {
    name: "Dan K.",
    location: "Pasadena, MD",
    text: "Had them replace our crumbling driveway. The new one looks amazing and they handled the whole permit process. Professional from start to finish.",
    service: "Driveway Installation",
    rating: 5,
  },
  {
    name: "Christine M.",
    location: "Edgewater, MD",
    text: "We hired them for fencing and hardscaping. Both projects were done beautifully and on budget. They communicated clearly every step of the way.",
    service: "Fencing",
    rating: 5,
  },
  {
    name: "Tom B.",
    location: "Arnold, MD",
    text: "Bobby's team handled our ADU project from excavation to finish. Having one contractor manage the whole thing saved us so much stress. Outstanding work.",
    service: "Accessory Dwelling Units",
    rating: 5,
  },
] as const;

export interface StampedConcreteStyle {
  name: string;
  slug: string;
  image: string;
  description: string;
}

export const STAMPED_CONCRETE_STYLES: StampedConcreteStyle[] = [
  { name: "Ashlar Slate", slug: "ashlar-slate", image: "/images/stamped-ashlar-slate.jpg", description: "Clean geometric slate pattern — our most popular choice for patios and pool decks" },
  { name: "Royal Ashlar", slug: "royal-ashlar", image: "/images/stamped-royal-ashlar.jpg", description: "Oversized stone blocks with deep grout lines for a bold, upscale look" },
  { name: "Random Stone", slug: "random-stone", image: "/images/stamped-random-stone.jpg", description: "Natural fieldstone layout with varied shapes — mimics real flagstone" },
  { name: "London Cobblestone", slug: "london-cobblestone", image: "/images/stamped-london-cobblestone.jpg", description: "Old-world cobblestone pattern that pairs beautifully with colonial homes" },
  { name: "Circle Cobblestone", slug: "circle-cobblestone", image: "/images/stamped-circle-cobblestone.png", description: "Circular cobble pattern — perfect for focal points and small patios" },
  { name: "Herringbone Brick", slug: "herringbone-brick", image: "/images/stamped-herringbone-brick.png", description: "Classic 45° herringbone brick — ideal for walkways and driveway aprons" },
  { name: "Herringbone Slate", slug: "herringbone-slate", image: "/images/stamped-herringbone-slate.jpg", description: "Slate texture in a herringbone layout for a refined, modern finish" },
  { name: "Basketweave Brick", slug: "basketweave-brick", image: "/images/stamped-basketweave-brick.jpg", description: "Traditional woven brick pattern — timeless and versatile" },
  { name: "18×18 Slate", slug: "18x18-slate", image: "/images/stamped-18x18-slate.png", description: "Large-format square slate tiles — clean, contemporary, and uniform" },
  { name: "Cesar Stone", slug: "cesar-stone", image: "/images/stamped-cesar-stone.jpg", description: "Irregular Mediterranean stone with a warm, rustic character" },
  { name: "Wood Plank", slug: "wood-plank", image: "/images/stamped-wood-plank.jpg", description: "Realistic wood-grain texture — the look of hardwood without the maintenance" },
  { name: "Mexican Tile", slug: "mexican-tile", image: "/images/stamped-mexican-tile.jpg", description: "Saltillo-style terra cotta tiles — brings a warm Southwestern feel" },
  { name: "Sea Shells", slug: "sea-shells", image: "/images/stamped-sea-shells.jpg", description: "Coastal shell-embedded texture — a unique accent for Chesapeake Bay homes" },
  { name: "Compass Medallion", slug: "compass-medallion", image: "/images/stamped-compass-medallion.jpg", description: "4-foot diameter compass rose inlay — a stunning centerpiece for any patio" },
];

export const GALLERY_ITEMS = [
  // ── Decks ──────────────────────────────────────────────────────────────────
  { src: "/images/wood-deck-construction-01.webp", alt: "Custom wood deck with railing overlooking wooded backyard in Anne Arundel County", category: "Decks", width: 1200, height: 800 },
  { src: "/images/deck-composite-railing-steps.jpg", alt: "Composite deck with black aluminum railing and wide steps in Maryland backyard", category: "Decks", width: 1200, height: 800 },
  { src: "/images/deck-multi-level-wood.jpg", alt: "Multi-level pressure treated wood deck with screened porch on wooded property", category: "Decks", width: 1200, height: 800 },
  { src: "/images/deck-cedar-pergola-dining.jpg", alt: "Cedar deck with white pergola and outdoor dining area at sunset", category: "Decks", width: 1200, height: 800 },
  { src: "/images/deck-ground-level-firepit.jpg", alt: "Ground-level composite deck with fire pit and Adirondack chairs in suburban backyard", category: "Decks", width: 1200, height: 800 },

  // ── Hardscaping ────────────────────────────────────────────────────────────
  { src: "/images/paver-walkway-interlocking-bricks-01.jpeg", alt: "Paver walkway with interlocking brick leading to front door in Maryland", category: "Hardscaping", width: 1000, height: 1300 },
  { src: "/images/retaining-wall-curved-garden-02.jpg", alt: "Curved block retaining wall with landscape lighting in Anne Arundel County", category: "Hardscaping", width: 1000, height: 1200 },
  { src: "/images/retaining-wall-stone-block-01.jpg", alt: "Stone block retaining wall with steps at residential home", category: "Hardscaping", width: 1000, height: 1200 },
  { src: "/images/paver-installation-concrete-stones-02.webp", alt: "Contractor laying interlocking paver stones for backyard patio", category: "Hardscaping", width: 1200, height: 800 },
  { src: "/images/stamped-ashlar-slate.jpg", alt: "Stamped concrete walkway with ashlar slate pattern and landscaping", category: "Stamped Concrete", width: 1200, height: 900 },
  { src: "/images/Back-patio-Back-Wall-Close-Up-rotated.webp", alt: "Stone patio retaining wall close-up detail in Maryland", category: "Hardscaping", width: 900, height: 600 },
  { src: "/images/Steps-7-Grey-Border-rotated.webp", alt: "Large concrete steps with grey border accent in Anne Arundel County", category: "Hardscaping", width: 800, height: 1200 },
  { src: "/images/hardscape-retaining-wall-concrete-pad.jpg", alt: "Stone block retaining wall with broom-finish concrete pad and steps", category: "Hardscaping", width: 1024, height: 768 },
  { src: "/images/hardscape-retaining-wall-corner-detail.jpg", alt: "Close-up of stone block retaining wall corner with concrete broom finish", category: "Hardscaping", width: 1024, height: 768 },
  { src: "/images/hardscape-waterfront-brick-retaining-wall.jpg", alt: "Brick retaining wall and stamped walkway at waterfront property in Maryland", category: "Hardscaping", width: 768, height: 1024 },
  { src: "/images/hardscape-stamped-walkway-to-dock.jpg", alt: "Stamped concrete walkway with grapevine pattern leading to boat dock", category: "Hardscaping", width: 768, height: 1024 },
  { src: "/images/hardscape-brick-retaining-wall-tiered.jpg", alt: "Multi-level brick retaining wall with stamped concrete walkway and steps", category: "Hardscaping", width: 768, height: 1024 },
  { src: "/images/hardscape-waterfront-paver-walkway.jpg", alt: "Stamped walkway and paver patio at marina waterfront property", category: "Hardscaping", width: 768, height: 1024 },
  { src: "/images/hardscape-dock-retaining-wall-steps.jpg", alt: "Retaining wall with steps connecting dock to paver patio at waterfront home", category: "Hardscaping", width: 1024, height: 768 },
  { src: "/images/hardscape-stamped-concrete-flagstone-patio.jpg", alt: "Stamped concrete patio with flagstone pattern and stone block wall", category: "Hardscaping", width: 768, height: 1024 },
  { src: "/images/hardscape-stamped-flagstone-wall-closeup.jpg", alt: "Close-up of wet-look sealed stamped concrete with stone retaining wall cap", category: "Hardscaping", width: 1024, height: 768 },
  { src: "/images/hardscape-curved-retaining-wall-tree.png", alt: "Curved stone retaining wall with drainage around established tree and front steps", category: "Hardscaping", width: 768, height: 1024 },

  // ── Stamped Concrete ───────────────────────────────────────────────────────
  { src: "/images/stamped-concrete-driveway-decorative-01.webp", alt: "Decorative stamped concrete driveway on upscale home in Maryland", category: "Stamped Concrete", width: 1200, height: 1200 },
  { src: "/images/stamped-concrete-img.webp", alt: "Round stamped concrete patio with fire pit in Anne Arundel County", category: "Stamped Concrete", width: 1200, height: 800 },
  { src: "/images/Patio-Red-Block-with-Compas-rotated.webp", alt: "Stamped concrete patio with decorative compass rose design", category: "Stamped Concrete", width: 1200, height: 900 },
  { src: "/images/hardscape-stamped-concrete-flagstone-patio.jpg", alt: "Stamped concrete patio with flagstone pattern and stone block retaining wall", category: "Stamped Concrete", width: 768, height: 1024 },
  { src: "/images/hardscape-stamped-flagstone-wall-closeup.jpg", alt: "Wet-look sealed stamped concrete patio with flagstone stamp pattern close-up", category: "Stamped Concrete", width: 1024, height: 768 },
  { src: "/images/hardscape-stamped-walkway-to-dock.jpg", alt: "Custom stamped concrete walkway with grapevine border leading to dock", category: "Stamped Concrete", width: 768, height: 1024 },
  { src: "/images/stamped-ashlar-slate.jpg", alt: "Ashlar slate stamped concrete pattern sample", category: "Stamped Concrete", width: 800, height: 600 },
  { src: "/images/stamped-royal-ashlar.jpg", alt: "Royal ashlar stamped concrete pattern sample", category: "Stamped Concrete", width: 800, height: 600 },
  { src: "/images/stamped-random-stone.jpg", alt: "Random stone stamped concrete pattern sample", category: "Stamped Concrete", width: 800, height: 600 },
  { src: "/images/stamped-london-cobblestone.jpg", alt: "London cobblestone stamped concrete pattern sample", category: "Stamped Concrete", width: 800, height: 600 },
  { src: "/images/stamped-herringbone-brick.png", alt: "Herringbone brick stamped concrete pattern sample", category: "Stamped Concrete", width: 800, height: 600 },
  { src: "/images/stamped-wood-plank.jpg", alt: "Wood plank stamped concrete pattern sample", category: "Stamped Concrete", width: 800, height: 600 },
  { src: "/images/stamped-cesar-stone.jpg", alt: "Cesar stone stamped concrete pattern sample", category: "Stamped Concrete", width: 800, height: 600 },
  { src: "/images/stamped-compass-medallion.jpg", alt: "Compass rose medallion stamped concrete inlay", category: "Stamped Concrete", width: 800, height: 600 },

  // ── Gravel Pads & Concrete Foundations ────────────────────────────────────
  { src: "/images/gravel-pad-shed-foundation-01.jpeg", alt: "Gravel pad foundation for shed next to vinyl fence in Maryland", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 900 },
  { src: "/images/gravel-pad-compacted-shed-13.webp", alt: "Compacted gravel pad installed next to large outbuilding", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 800 },
  { src: "/images/concrete-slab-foundation-poured-01.webp", alt: "Freshly poured concrete slab foundation in Anne Arundel County", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 800 },
  { src: "/images/playground-mulch-surfacing-01.webp", alt: "Playground equipment pad installation with safety surfacing", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 800 },
  { src: "/images/gravel-pad-timber-white-stone.jpg", alt: "Timber-framed gravel pad with white crushed stone near vinyl fence", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 800 },
  { src: "/images/gravel-pad-large-lot-summer.jpg", alt: "Large crushed stone gravel pad on open residential lot in summer", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 900 },
  { src: "/images/gravel-pad-wooded-lot-fall.jpg", alt: "Timber-framed gravel pad on wooded lot in fall — Anne Arundel County", category: "Gravel Pads & Concrete Foundations", width: 768, height: 1024 },
  { src: "/images/gravel-pad-horse-barn-large.jpg", alt: "Large stone dust gravel pad for horse barn on rural Maryland property", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 900 },
  { src: "/images/gravel-pad-horse-barn-stone-dust.jpg", alt: "Oversized gravel pad with stone dust finish for equestrian barn", category: "Gravel Pads & Concrete Foundations", width: 1200, height: 900 },
  { src: "/images/gravel-pad-two-level-foundation.webp", alt: "Two-level gravel shed foundation with timber frame on sloped lot", category: "Gravel Pads & Concrete Foundations", width: 1400, height: 788 },
  { src: "/images/gravel-pad-installation-process.webp", alt: "Gravel pad foundation installation in progress on residential property", category: "Gravel Pads & Concrete Foundations", width: 1400, height: 788 },

  // ── Excavation & Demolition ────────────────────────────────────────────────
  { src: "/images/excavation-site-grading-backhoe-01.webp", alt: "Backhoe excavating and grading residential property in Maryland", category: "Excavation & Demolition", width: 1200, height: 800 },
  { src: "/images/mini-excavator-equipment-01.webp", alt: "Backyard Bobby's Toro Dingo mini excavator ready for site work", category: "Excavation & Demolition", width: 900, height: 1200 },
  { src: "/images/excavation-foundation-digging-02.webp", alt: "Mini excavator digging foundation next to residential home", category: "Excavation & Demolition", width: 1200, height: 800 },
  { src: "/images/drainage-trench-french-drain-01.webp", alt: "French drain trench installation for yard drainage in Anne Arundel County", category: "Excavation & Demolition", width: 1200, height: 800 },
  { src: "/images/excavation-site-grading-residential.jpg", alt: "Mini excavator grading residential backyard for patio preparation", category: "Excavation & Demolition", width: 1200, height: 800 },

  // ── Fencing ────────────────────────────────────────────────────────────────
  { src: "/images/service-fencing.png", alt: "Wood privacy fence installation at residential home in Maryland", category: "Fencing", width: 1024, height: 576 },
  { src: "/images/fence-wood-privacy-horizontal.jpg", alt: "Horizontal cedar privacy fence along residential property line in Anne Arundel County", category: "Fencing", width: 1200, height: 800 },
  { src: "/images/fence-vinyl-white-privacy.jpg", alt: "White vinyl privacy fence surrounding suburban backyard with mature trees", category: "Fencing", width: 1200, height: 800 },
  { src: "/images/fence-aluminum-black-ornamental.jpg", alt: "Black aluminum ornamental fence with spear-top pickets at Maryland home", category: "Fencing", width: 1200, height: 800 },
  { src: "/images/fence-board-on-board-cedar.jpg", alt: "Board-on-board cedar privacy fence in suburban backyard with landscaping", category: "Fencing", width: 1200, height: 800 },

  // ── Driveway Installation ──────────────────────────────────────────────────
  { src: "/images/service-driveway-installation.png", alt: "Professional concrete driveway installation in Anne Arundel County", category: "Driveway Installation", width: 1024, height: 576 },
  { src: "/images/driveway-asphalt-new-residential.jpg", alt: "Freshly paved asphalt driveway at single family home with two car garage", category: "Driveway Installation", width: 1200, height: 800 },
  { src: "/images/driveway-concrete-exposed-aggregate.jpg", alt: "Exposed aggregate concrete driveway with stone border at residential home", category: "Driveway Installation", width: 1200, height: 800 },
  { src: "/images/driveway-paver-brick-pattern.jpg", alt: "Herringbone pattern brick paver driveway leading to three car garage", category: "Driveway Installation", width: 1200, height: 800 },
  { src: "/images/driveway-gravel-crushed-stone.jpg", alt: "Compacted crushed stone gravel driveway on rural Maryland property", category: "Driveway Installation", width: 1200, height: 800 },

  // ── Roofing ────────────────────────────────────────────────────────────────
  { src: "/images/roof-architectural-shingles-colonial.jpg", alt: "Charcoal architectural shingle roof replacement on colonial home", category: "Roofing", width: 1200, height: 800 },
  { src: "/images/roof-installation-crew-working.jpg", alt: "Roofing crew installing new shingles on residential home in Maryland", category: "Roofing", width: 1200, height: 800 },
  { src: "/images/roof-ranch-home-brown-shingles.jpg", alt: "Brown dimensional shingle roof on ranch-style home with new gutters", category: "Roofing", width: 1200, height: 800 },

  // ── Accessory Dwelling Units ───────────────────────────────────────────────
  { src: "/images/service-accessory-dwelling-unit.png", alt: "Modern accessory dwelling unit built in residential backyard", category: "Accessory Dwelling Units", width: 1024, height: 576 },
  { src: "/images/adu-modern-backyard-cottage.jpg", alt: "Modern cedar ADU cottage with large windows and stone walkway in backyard", category: "Accessory Dwelling Units", width: 1200, height: 800 },
  { src: "/images/adu-guest-house-craftsman.jpg", alt: "Craftsman-style guest house ADU with covered porch and flagstone path", category: "Accessory Dwelling Units", width: 1200, height: 800 },
  { src: "/images/adu-construction-framing.jpg", alt: "Accessory dwelling unit framing stage on concrete foundation in residential backyard", category: "Accessory Dwelling Units", width: 1200, height: 800 },
  { src: "/images/adu-studio-office-modern.jpg", alt: "Contemporary detached home office studio with sliding glass doors", category: "Accessory Dwelling Units", width: 1200, height: 800 },
] as const;

export type GalleryItem = (typeof GALLERY_ITEMS)[number];
